name: Test

on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test-Action
    steps:
      - uses: actions/checkout@v3
      # test1
      # - id: test1
      #   uses: Entepotenz/change-string-case-action-min-dependencies@v1
      #   with:
      #     string: 'XyZzY'
      - name: test1
        uses: ./
        with:
          string: 'XyZzY'
      - name: bla
        run: |
          echo "${{ steps.test1.outputs.lowercase }}"
          echo "${{ steps.test1.outputs.uppercase }}"
          echo "${{ steps.test1.outputs.capitalized }}"
      - name: bla2
        run: |
          env
      - name: Assert
        if: |
          ${{ steps.test1.outputs.lowercase != 'xyzzy' || 
            steps.test1.outputs.uppercase != 'XYZZY' ||
            steps.test1.outputs.capitalized != 'Xyzzy' }}
        uses: actions/github-script@v7
        with:
          script: |
              core.setFailed('test1 failed; \
                lowercase="${{ steps.test1.outputs.lowercase }}"; \
                uppercase="${{ steps.test1.outputs.uppercase }}"; \
                capitalized="${{ steps.test1.outputs.capitalized }}"')
      # test2
      # - id: test2
      #   uses: Entepotenz/change-string-case-action-min-dependencies@v1
      #   with:
      #     string: 'xyZzY'
      - name: test2
        uses: ./
        with:
          string: 'xyZzY'
      - name: Assert
        if: |
          ${{ steps.test2.outputs.lowercase != 'xyzzy' || 
            steps.test2.outputs.uppercase != 'XYZZY' ||
            steps.test2.outputs.capitalized != 'Xyzzy' }}
        uses: actions/github-script@v7
        with:
          script: |
              core.setFailed('test2 failed; \
                lowercase="${{ steps.test2.outputs.lowercase }}"; \
                uppercase="${{ steps.test2.outputs.uppercase }}"; \
                capitalized="${{ steps.test2.outputs.capitalized }}"')
      # test3
      # - id: test3
      #   uses: Entepotenz/change-string-case-action-min-dependencies@v1
      #   with:
      #     string: 'ÄxÖöZzx%Z'
      - name: test3
        uses: ./
        with:
          string: 'ÄxÖöZzx%Z'
      - name: Assert
        if: |
          ${{ steps.test3.outputs.lowercase != 'äxöözzx%z' || 
            steps.test3.outputs.uppercase != 'ÄXÖÖZXX%Z' ||
            steps.test3.outputs.capitalized != 'Äxöözzx%z' }}
        uses: actions/github-script@v7
        with:
          script: |
              core.setFailed('test3 failed; \
                lowercase="${{ steps.test3.outputs.lowercase }}"; \
                uppercase="${{ steps.test3.outputs.uppercase }}"; \
                capitalized="${{ steps.test3.outputs.capitalized }}"')